AWSTemplateFormatVersion: "2019-09-09"
Transform: AWS::Serverless-2016-10-31
Description: API de Envios, Trabajo Practico 3, Cloud Computing
Resources:
  Envio:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: 100
      Events:
        ListEnviosPendientes:
          Type: Api
          Properties:
            Path: /envios/pendientes
            Method: get
        CreateEnvio:
          Type: Api
          Properties:
            Path: /envios
            Method: post
        MarcarEnviado:
          Type: Api
          Properties:
            Path: /envios/{idEnvio}/entregado
            Method: put
